# These are supported funding model platforms

github: "amirihusayn" # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [uer1, user2]
custom: ['https://www.coffeete.ir/amirihusayn'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
