title: کامپیوتر صنعتی ارومیه
email: ceit.uut@gmail.com
tagline: انجمن علمی کامپیوتر صنعتی ارومیه
description: >- # this means to ignore newlines until "baseurl:"
  انجمن علمی کامپیوتر و فناوری اطلاعات دانشگاه صنعتی ارومیه
locale: fa_IR
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codegeeks.ir" # the base hostname & protocol for your site
repo: "ceituut.github.io"
github_username: ceituut
social:
  name: انجمن کامپیوتر صنعتی ارومیه
  links:
    - https://t.me/ceit_uut
    - https://www.instagram.com/ceit_uut
    - https://www.youtube.com/channel/UCVHy7Dv9vkf3zt0_P2J5vLw


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections settings
collections_dir: collections
collections:
  authors:
    output: true
    permalink: /:collection/:name
  members:
    output: false
    permalink: /:collection/:name
  faqs:
    output: true
    permalink: /:collection/:name
  events:
    output: true
    permalink: /:collection/:name
  code-challenge:
    output: true
    permalink: /:collection/:name

# Default frontmatter settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      back: "/index.html"

  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: "about.html"
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: "blog.html"
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: "contests.html"
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: "events.html"
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: "faqs.html"
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      back: "/blog.html"

  - scope:
      path: ""
      type: "faqs"
    values:
      layout: "page"
      back: "/faqs.html"

  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      back: "/events.html"

  - scope:
      path: ""
      type: "code-challenge"
    values:
      layout: "contest"
      back: "/contests.html"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      back: "/blog.html"